// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj3eR_62gp8kOMQmeDKe_7UsYIi2rVdNk',
    appId: '1:860997172903:web:9e8e9de9174a993026e582',
    messagingSenderId: '860997172903',
    projectId: 't35t-32882',
    authDomain: 't35t-32882.firebaseapp.com',
    databaseURL: 'https://t35t-32882-default-rtdb.firebaseio.com',
    storageBucket: 't35t-32882.firebasestorage.app',
    measurementId: 'G-E111M1N516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVHAPSa_AhEeWCipES0S8gh2QNdE2lkHk',
    appId: '1:860997172903:android:1186e8c773b00bcc26e582',
    messagingSenderId: '860997172903',
    projectId: 't35t-32882',
    databaseURL: 'https://t35t-32882-default-rtdb.firebaseio.com',
    storageBucket: 't35t-32882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcclNYItbomMkhW3J3iGLQHoPybG0F63o',
    appId: '1:860997172903:ios:9d69252efcaefe7f26e582',
    messagingSenderId: '860997172903',
    projectId: 't35t-32882',
    databaseURL: 'https://t35t-32882-default-rtdb.firebaseio.com',
    storageBucket: 't35t-32882.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcclNYItbomMkhW3J3iGLQHoPybG0F63o',
    appId: '1:860997172903:ios:9d69252efcaefe7f26e582',
    messagingSenderId: '860997172903',
    projectId: 't35t-32882',
    databaseURL: 'https://t35t-32882-default-rtdb.firebaseio.com',
    storageBucket: 't35t-32882.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj3eR_62gp8kOMQmeDKe_7UsYIi2rVdNk',
    appId: '1:860997172903:web:de49db24a03e229726e582',
    messagingSenderId: '860997172903',
    projectId: 't35t-32882',
    authDomain: 't35t-32882.firebaseapp.com',
    databaseURL: 'https://t35t-32882-default-rtdb.firebaseio.com',
    storageBucket: 't35t-32882.firebasestorage.app',
    measurementId: 'G-GD6D4DVSXN',
  );
}
